version: '3'
services:

#  broker:
#    build: ./broker
#    port:
#    - "8080:8080"
#    depends_on:
#      - racegenerator
#      - racesimulator
#      - oddsbuilder
#
#  racegenerator:
#    build: ./racegenerator
#    ports:
#      - "8083:8083"
#
#  racesimulator:
#    build: ./racesimulator
#    ports:
#      - "8081:8081"
#
#  oddsbuilder:
#    build: ./oddsbuilder
#    ports:
#      - "8082:8082"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    environment:
      MONGO_INITDB_DATABASE: blt