version: '3'
services:
#  broker:
#    build: betBroker
#  service1:
#    build: service1
#  service2:
#    build: service2
#  service3:
#    build: service3

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    environment:
      MONGO_INITDB_DATABASE: blt