version: '3'
services:

  bookie:
    build: ./bookie
    ports:
    - "8080:8080"
    depends_on:
      - racegenerator
      - racesimulator
      - oddsbuilder
    networks:
      - backend

  racegenerator:
    build: ./racegenerator
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/blt
    depends_on:
      - mongo
    networks:
        - backend

  racesimulator:
    build: ./racesimulator
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/blt
    networks:
        - backend

  oddsbuilder:
    build: ./oddsbuilder
    ports:
      - "8082:8082"
    networks:
        - backend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    environment:
      MONGO_INITDB_DATABASE: blt
    networks:
      - backend


networks:
  backend:
    driver: bridge