apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookie-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bookie
  template:
    metadata:
      labels:
        app: bookie
    spec:
      containers:
        - name: bookie
          image: brendansadlier/blt-bookie:latest
          ports:
            - containerPort: 8080
