# oddsbuilder-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oddsbuilder-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oddsbuilder
  template:
    metadata:
      labels:
        app: oddsbuilder
    spec:
      containers:
        - name: oddsbuilder
          image: brendansadlier/blt-oddsbuilder:latest
          ports:
            - containerPort: 8082
