apiVersion: apps/v1
kind: Deployment
metadata:
  name: racegenerator-deployment
spec:
  replicas: 2  # Adjust the number of replicas based on your requirements
  selector:
    matchLabels:
      app: racegenerator
  template:
    metadata:
      labels:
        app: racegenerator
    spec:
      containers:
        - name: racegenerator
          image: brendansadlier/blt-racegenerator:latest  # Replace with your Docker image
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongo-service:27017/blt
