# racegenerator-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: racegenerator-service
spec:
  type: ClusterIP
  selector:
    app: racegenerator
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083